### ISSUE TITLE
Collection grid: inline edits

### ISSUE THREAD

**Issue by practual** [donsplume/TinStreet-client#1]
Provide an inline 'spreadsheet style' method for editing attributes of a collection item in the grid. This will mean rows don't have to be deleted and re-added with different characteristics.

Maybe clicking on the field can turn it into a text box for editing the value?

**Comment by area** [comment]
Should this work for all fields apart from the name of the card?

Presumably, this should only work for privately hosted objects?

**Comment by practual** [comment]
I'd have thought it should work for all fields including name - everything else might still be correct.

And yes, if there's a non-zero hosted position, you shouldn't be able to edit.

**Comment by area** [comment]
How much validation should take place clientside? How forced should it
be? For example, I have a foil Masters Edition Underground Sea. I change
the set to Revised. Should foil 'unset' itself, and refuse to be able to
be toggled on? What should happen to the 'Online' condition?

**Comment by donsplume** [comment]
Maybe a user-specific setting? i.e. in one mode the dodgy fields (e.g. foil, condition) are highlighted and the user can click in the field to correct them, and in the other mode, it would just wipe the values or set them to the only available option (where there is only a single possible value).

In the first mode, if the field is in error, it should still be submittable, but without the associated instrument/printing code (i.e. you wipe it), otherwise the server will reject it on validation grounds.

**Comment by practual** [comment]
As discussed separately, the behaviour should be as follows:

When editing a field, all other fields are left untouched, but may be highlighted to show if they are in an error/inconsistent state.

A full list of instruments is needed for the selected card to provide the user with sufficient options for editing each field. This list may need to be refreshed if the user edits the card field.

A hierarchy of fields is to be established for showing fields in error, with fields low in the hierarchy showing in error instead of fields high in the hierarchy. The hierarchy is 1) card (i.e. card is never shown to be in error), 2) expansion, 3) printing number, 4) foil status, 5) condition.

When editing a field, all valid options are shown given the values of fields further up the hierarchy. The field will therefore not be in error unless a change is made further up the hierarchy.

For the example given above, if a foil, online condition, Masters Edition Underground Sea is edited to be Revised, both 'foil' and 'condition' fields are shown in error. Attempts to edit the fields will only allow valid values to be selected (i.e. only allow non-foil to be selected and physical conditions). Of course, nullifying the error fields is also a valid action by the user.

A row with fields in error can still be submitted and saved on the server, but the submission should not include instrument and/or printing code fields associated with the error - e.g. if condition is in error, the instrument code should not be sent, as this will get rejected by the server.

**Comment by practual** [comment]
Closed with [08144ed](https://github.com/donsplume/TinStreet-client/commit/08144ed022a57d575b9756a7e955e4c856ecffa2).
